project:
  type: book
  output-dir: docs

lang: fr

website:
  favicon: images/logoUP.png

book:
  title: "Statistiques Fondamentales"
  author: "Simon Coste"
  date: today
  repo-url: "https://github.com/statsfonda/site"
  downloads: pdf
  chapters:
     - index.qmd
     - content/ch1.qmd
     - content/ch2.qmd
     - content/ch2_1.qmd
     - content/ch2_ex.qmd
     - content/ch3.qmd
     - content/ch31_outils.qmd
     - content/ch3_ex.qmd
     - content/ch4_0.qmd
     - content/ch4_1.qmd
     - content/ch4_2.qmd
     - content/ch4_ex.qmd
     - content/ch5_0.qmd 
     - content/ch5_01.qmd
     - content/ch5_1.qmd
     - content/ch5_2.qmd
     - content/ch5_ex.qmd
     - content/ch6_0.qmd
     - content/ch6_1.qmd
     - content/ch6_2.qmd
     - content/ch6_ex.qmd
     - content/ch6_3.qmd
     - content/ch6_4.qmd
     - content/problemes.qmd
     - content/ch7_0.qmd
     - content/ch7_1.qmd
     - content/ch7_ex.qmd
     - content/references.qmd
     - content/ref.qmd
     - content/app1.qmd
     - content/app2.qmd
  sidebar:
    #style: docked
    logo: "images/logoUP.png"

bibliography: utils/references.bib

format:
  html:
    mainfont: "Computer Modern Serif"
    theme:
      light: united
    css: utils/styles.css
    include-before-body:
      - utils/macros



  pdf:
    documentclass: scrreport
    fontsize: "10"
    margin-left: 2cm
    margin-right: 2cm
    margin-bottom: 3cm
    margin-top: 2cm
    include-in-header:
      - utils/macros.tex
    


jupyter: julia-1.9